### ISSUE TITLE
Cannot convert to CSV: add_non_dynasty

### ISSUE THREAD

**Issue by teknotoast** [blastentwice/CK3-Family-Tree-Exporter-To-Gramps#2]
Error: Traceback (most recent call last):
  File "C:\Users\deast\AppData\Local\Temp\onefile_12368_133708127983459424\main.py", line 51, in run
  File "C:\Users\deast\AppData\Local\Temp\onefile_12368_133708127983459424\character.py", line 327, in char_main
  File "C:\Users\deast\AppData\Local\Temp\onefile_12368_133708127983459424\character.py", line 107, in add_non_dynasty

Converts save to JSON fine, however, I cannot convert the tree of any characters of the main dynasty of this save to CSV.  Cadet houses convert to CSV fine, non-dynastic houses convert to CSV fine, but my main dynasty absolutely will not, no matter the character I choose.

I've had success in using the app with other saves. I've tried using the older version of rakaly (same effect). I've also tried using the older version of the converter entirely, but nothing worked there.

**Comment by blastentwice** [comment]
We resolved this issue and a beta version is released in the discord. A more complete update will be pushed after the dlc release.

**Comment by blastentwice** [comment]
We resolved this issue and a beta version is released in the discord. A more complete update will be pushed after the dlc release.

**Comment by blastentwice** [comment]
Will keep this issue open until it is implemented in the main update.
